project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", RedirectView.as_view(pattern_name="web:playlist_list"), name="home"),  # Create a new path for the home page
    path("accounts/", include("accounts.urls")),  # It is very important to include this BEFORE the built-in authentication URLs
    path("accounts/", include("django.contrib.auth.urls")),  # Add the path for the built-in authentication URLs
    path('musicterritory/', include('web.urls')),
]

web/urls.py
from django.urls import path, include
from django.utils import timezone
from django.views.generic import DetailView, ListView

from web import views
from web.forms import PlaylistForm
from web.views import PlaylistCreate, PlaylistDetail, LoginRequiredCheckIsOwnerUpdateView, SongCreate, PlaylistList, DeletePlaylist, SongDelete, search_playlists
from web.models import Song, Playlist

app_name = "web"

urlpatterns = [

    path('',
         PlaylistList.as_view(),
         name='playlist_list'),

    path('playlists/<int:pk>/delete',
         DeletePlaylist.as_view(),
         name='playlist_delete'),

    #Playlist details, ex.: /playlists/1/
    path('playlists/<int:pk>',
         PlaylistDetail.as_view(),
         name='playlist_detail'),

    #Playlist song details, ex: /songs/1/
    path('songs/<int:pk>',
         DetailView.as_view(
             model=Song,
             template_name = 'song_detail.html'),
         name='song_detail'),

    #Create a playlist, /playlists/create/
    path('playlists/create',
         PlaylistCreate.as_view(),
         name='playlist_create'),

    #Edit playlist details, ex.: /playlists/1/edit/
    path('playlists/<int:pk>/edit',
        LoginRequiredCheckIsOwnerUpdateView.as_view(
            model=Playlist,
            form_class=PlaylistForm),
        name='playlist_edit'),

    # Create a playlist, ex.: /musicterritory/playlists/1/songs/create/
    path('playlists/<int:pk>/songs/create',
         SongCreate.as_view(),
         name='song_create'),

    ##path('playlists/<int:pk>/songs/add_song', add_song, name='add_song'),

    path('playlists/<int:pk>/songs/<int:pkr>/delete',
         SongDelete.as_view(),
         name='song_delete'),

    path('search_playlists/', search_playlists, name='search_playlists'),

    path('songs/<int:pk>/', views.SongDetailView.as_view(), name='song_detail'),


]

templates/add_song.html
{% extends "base.html" %}
{% load static %}
{% block title %}Búsqueda de Canciones{% endblock %}
{% block content %}
    <div style="display: flex; justify-content: center; align-items: center">
        <input class="search-input" type="text" id="searchInput" name="search"
               placeholder="Search for songs, artists, etc."
               onkeydown="if (event.keyCode == 13) buscarCancion()"><!--Per buscar al apretar ENTER-->
        <button class="genericButton searchButton" onclick="buscarCancion()">Search</button>
    </div>
    <div id="searchResults"></div>
{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'javascript/searchFiveSongs.js' %}"></script>
{% endblock %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}

<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Tutorial projecte web{% endblock %}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'images/logo2.png' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'images/logo2.png' %}" type="image/x-icon">

</head>

<body>
<div class="header">
    <img src="{% static 'images/logo2.png' %}" class="logo">
    <a href="/musicterritory/">
        <button class="genericButton h1">
            <h1>MusicTerritory</h1>
        </button>
    </a>
</div>

<div id="sidebar">
    {% block sidebar %}

    {% endblock %}
</div>

<div id="content">
    {% block content %}
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% endblock %}
</div>

</body>

</html>

templates/form.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="login-form" style="justify-content: center">
    <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {% for field in form %}
            <tr>
                <td>
                    <div style="margin: 10px;">
                        <label style="font-size: 1.2em;">{{ field.label_tag }}</label>
                        <div style="font-size: 0.8em; resize: none">{{ field }}</div>
                    </div>
                </td>
            </tr>
            {% endfor %}
        </table>
        <button class="genericButton" type="submit">Create</button>
    </form>
</div>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div class="separator"></div>
<div class="top-container">
    <h2>Hi {{ user.username }}!</h2>
  <form action="{% url 'logout' %}" method="post">  <!--Formulario para cerrar sesión-->
    {% csrf_token %}
    <button class="genericButton logoutButton" type="submit">Log Out</button>
  </form>
</div>

<div class="separator"></div>

<div class="row">
    <div class="column" style="background-color:#aaa;">
        <form action="{% url 'web:playlist_create' %}" method="get">
            <div style="display: flex; justify-content: center; align-items: center">
                <h1>My Playlists</h1>
                {% if user.is_authenticated %}
                    <button class="genericButton large-button" type="submit">New Playlist</button>
                {% endif %}
            </div>
        </form>
        <ul>
            {% if user.is_authenticated %}
                {% for playlist in user_playlists %}
                    <li>
                        <div style="display: flex; justify-content: space-between;align-items: center">
                            <a  class="playlistButton myplaylists" href="{% url 'web:playlist_detail' playlist.id %}">{{ playlist.name }}</a>
                            {% if playlist.user == user %}
                            <a class="deleteButton" data-pk={{playlist.name}} style="height: 12px" href="{% url 'web:playlist_delete' playlist.id %}">Delete</a>
                            {% endif %}
                        </div>
                    </li>
                {% empty %}
                    <li>Sorry, you don't have any playlists yet.</li>
                {% endfor %}
            {% else %}
                <li>Sorry, you have to log in.</li>
            {% endif %}
        </ul>
        <div style="display: flex; justify-content: center; align-items: center">
            <h1>All Playlists</h1>
        </div>
        <ul>
            {% for playlist in all_playlists %}
                <li><a  class="playlistButton allplaylists" href="{% url 'web:playlist_detail' playlist.id %}">{{ playlist.name }}</a></li>
            {% empty %}
                <li>Sorry, no playlists registered yet.</li>
            {% endfor %}
        </ul>
    </div>
    <div class="column" style="background-color:#bbb;">
        <form>
            <input class="search-input" type="text" id="searchPlaylist" placeholder="Search playlists"
               onkeydown="if (event.keyCode == 13) buscarPlaylist(event)">
            <button class="genericButton" onclick="buscarPlaylist(event)">Search</button>
        </form>
        <div id="results"></div>

        {% block scripts %}
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="{% static 'javascript/searchFiveSongs.js' %}"></script>
        <script src="{% static 'javascript/searchPlaylists.js' %}"></script>
        {% endblock %}
    </div>
</div>


{% else %}

<div class="container-home">
    <h2>Bienvenido</h2>
    <p>Por favor, inicia sesión o regístrate</p>
    <div class = "container-home-buttons">

        <form action="{% url 'login' %}" method="post"> <!-- We can add a form to log out here -->
            {% csrf_token %}
            <button class="genericButton loginButton" type="submit">Log In</button>
        </form>
        <form action="{% url 'signup' %}" method="post"> <!-- We can add a form to log out here -->
            {% csrf_token %}
            <button class="genericButton" type="submit">Sign Up</button>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/playlist_confirm_delete.html
{% extends "base.html" %}
{% block content %}
<h1 style="color: white">Confirm Deletion</h1>
<div class="container" style="display: flex; justify-content: center; align-items: center; flex-direction: column">
    <p>Are you sure you want to delete the playlist "{{ playlist.name }}"?</p>
    <form method="post">
      {% csrf_token %}
      <button class="deleteButton" type="submit">Yes, delete</button>
      <a style="color: white" href="{% url 'web:playlist_list' %}">Cancel</a>
    </form>
</div>
{% endblock %}

templates/playlist_detail.html
{% extends "base.html" %}

{% block title %}Detalles de la Playlist{% endblock %}

{% block content %}
<span vocab="https://schema.org/" typeof="MusicPlaylist">
<div class="container">
    <div class="playlist-header" style="display: flex; flex-direction: column; justify-content: center; align-items: center">
        <h1 class="PlaylistName"><span property="name"> {{ playlist.name }}</span></h1>
            <p style="color: white;">
                Genre/s:
                {% with genres=playlist.genres.all  %}
                    {% for genre in genres %}
                        {% if not forloop.last %}
                            {{ genre }},
                        {% else %}
                            <span property="genre">{{ genre }}</span>
                        {% endif %}
                    {% endfor %}
                {% endwith %}
            </p>

        <p class="description">Description: <span property="description"> {{playlist.description}}</span></p>
        <p class="user_id">Playlist created by:<span property="creator"> {{playlist.user}}</span></p>
        <span  property="dateCreated" content="{{playlist.date}}"> </span>
        {% if user.is_authenticated and user == playlist.user %}
            <div style="display: flex; justify-content: center; align-items: center">
                <a href="{% url 'web:playlist_edit' playlist.id %}">
                    <button class="genericButton">Edit Playlist</button>
                </a>
                <a href="{% url 'web:song_create' playlist.id %}">
                    <button class="genericButton addSongButton">Add Song</button>
                </a>
            </div>
        {% endif %}
    </div>
    <p>
        {% with playlist.songs.all|length as songCount %}
        <span property="numTracks" content="{{ songCount }}">
        </span>
        {% endwith %}
    </p>



    <ul class="cançons" rel="tracks">
    {% for song in playlist.songs.all %}
        <li style="list-style-type:none" resource="#song{{song.pk}}" typeof="MusicRecording">
            <div class="playlistButton" style="display: flex; justify-content: space-between; align-items: center">
                <img style="height: 40px; width: 40px; border-radius: 10px" src="{{ song.url_imagen }}" alt="Song Image" property="image">
                <!-- Enlace al detalle de la canción -->
                <span property="name" content = "{{ song.title }}"></span>
                <a style="text-decoration: none; font-size: 20px;" href="{% url 'web:song_detail' pk=song.pk %}" class="Paragraf1">{{ song.title }} </a>
                <p style="color: white;">
                    {% for artist in song.artists.all %}
                       <span property="byArtist" resource="#artist{{artist.pk}}" typeof="MusicGroup">
                                <span property="name">{{ artist.name }}</span>
                            </span>
                    {% endfor %}
                </p>
                {% if user.is_authenticated and user == playlist.user %}
                    <form action="{% url 'web:song_delete' playlist.id song.id %}" method="POST" class="inline">
                        {% csrf_token %}
                        <button type="submit" class="deleteButton">Delete</button>
                    </form>
                {% endif %}
            </div>
        </li>
    {% endfor %}
    </ul>
</div>
</span>
{% endblock %}

templates/song_detail.html
<!-- song_detail.html -->
{% extends "home.html" %}
{% block title %}Song Detail - {{ song.title }} {% endblock %}

{% block content %}

<span vocab="https://schema.org/" resource="#song{{song.pk}}" typeof="MusicRecording">
    <div class="row">
        <div class="column" style="background-color:#424949">
            <img style="height: 220px; width: 220px; float: right;" src="{{ song.url_imagen }}" alt="Song Image" property="image">
        </div>
        <div class="column" style="background-color:#424949" >
            <h1 style="text-align: left; color: white" property="name">{{ song.title }}</h1>
            <p><strong>Artists:</strong>
                {% for artist in song.artists.all %}
                    <span property="byArtist" resource="#artist{{artist.pk}}" typeof="MusicGroup">
                                <span property="name">{{ artist.name }}</span>
                            </span>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p property="inAlbum"><strong>Album:</strong> {{ song.album }}</p>
            <p property="duration"><strong>Duration:</strong> {{ song.duration }}</p>
            <p property="archivedAt"><strong>URL:</strong> <a style="color: #4ac1f7" href="{{ song.url_cancion }}">{{ song.url_cancion }}</a></p>
        </div>
    </div>
</span>
{% endblock content %}